name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 13.247.59.15
          port: 22
          username: mnine
          key: ${{secrets.PRIVATE_KEY}}
          script: "cd www; git pull origin master; php artisan migrate --seed;"
